### ISSUE TITLE
Plugin has crashed

### ISSUE THREAD

**Issue by Curotos** [Riku55/galaxy-integration-n64-RetroArch-#1]
I just installed the plugin and set everything up but when I went into gog and tried to connect it, it said plugin has crashed try again. Any help would be much appreciated!

**Comment by riku55** [comment]
Sure. Did you add the "/" at the end of the paths in user_config? If you could show me your user_config.py file and the log (located at: C:\ProgramData\GOG.com\Galaxy\log\plugin-n64-a3824d31-c2d3-4a1a-b321-7d0764da5513.log), I will propably find the problem :)

**Comment by Curotos** [comment]
Here is the config file, I couldn't find the log tho? 
![Annotation 2019-10-14 111909](https://user-images.githubusercontent.com/54136079/66763025-17d61080-ee75-11e9-9808-f7519e4ed24f.png)

**Comment by riku55** [comment]
You need to put the path between the quotation marks, not after them.
So it should look like this:
rom_path = "F:/Emulators/ROMS/Nintendo64/"
emu_path= "F:/Retroarch/retroarch.exe/"

I fixed the missing mark in the example and I added some text for clarification :)

Also the ProgramData folder is invisible, so that's why you might not have found it. You can access it by entering %ProgramData% into the windows search or set invisible folders to be visible.

**Comment by Curotos** [comment]
Ah I gotcha, it fixed it so its now showing the platform on galaxy but none of my games imported? Sorry to keep being a bother

**Comment by riku55** [comment]
No problem, I had nobody to test the integration besides myself, so problems might happen.

Also I just noticed that you entered the. exe into the emu path, the .exe is not needed.
So it should just be
emu_path= "F:/Retroarch/"
try that and restart the integration.

**Comment by Curotos** [comment]
I tried it and the games have still not imported?

**Comment by riku55** [comment]
Edit: Talked about it on discord, problem was an old version of RetroArch that doesn't use JSON format for the playlist. So updating RetroArch solved the problem. Added required version to the readme.
